### ISSUE TITLE
Do NOT inline JavaScript in view

### ISSUE THREAD

**Issue by olivierobert** [bankkeez/course_management#14]
The registration page relies on [some inline JS](Pundit::NotAuthorizedError) to toggle the display of some form elements:

![Screen Shot 2563-05-18 at 13 13 58](https://user-images.githubusercontent.com/696529/82179881-8f878480-9909-11ea-92ce-877e60177162.png)

Instead, place all JS code in `app/assets/javascript`. The current implementation would also break the functionality of `registrations/_edit.haml` used when there is a registration error.

**Comment by bankkeez** [comment]
I have moved the inline JavaScript code to the `app/assets/javascript/registration.js`. Thank you for the advice.
