### ISSUE TITLE
Missing unit and system tests

### ISSUE THREAD

**Issue by olivierobert** [bankkeez/course_management#15]
As part of the assignment, we would like you to demonstrate your abilities to learn to write automated tests as well. So you need to add unit tests for models and one system test for one of the main features.

**Comment by bankkeez** [comment]
I've added unit tests and it every units work just fine until when I've added some system tests, `course_test.rb` just stop functioning with this error:
```
CourseTest#test_should_get_course(s)_from_a_single_instructor [/Users/bank/Desktop/workspace/course_management/test/models/course_test.rb:7]:
Expected: ["Spy course"]
  Actual: []
```
Actually this is correct but I don't understand how the system test ruined this?

**Comment by bankkeez** [comment]
The problem comes from assigning id to course fixtures, removing it and everything run smoothly.
